# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'discordclient.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1062, 798)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow {\n"
"background-color: #222224;\n"
"}\n"
"QTabWidget {\n"
"border: 1px solid black;\n"
"}\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 2px solid grey;\n"
"    background: #32CC99;\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: white;\n"
"    min-width: 20px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 2px solid grey;\n"
"    background: #32CC99;\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: #222224;\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.setObjectName("tab_home")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_home)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_left = QtWidgets.QFrame(self.tab_home)
        self.frame_left.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_left.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_left.setStyleSheet("QFrame {\n"
"background-color: #2F3136;\n"
"border-right: 0px;\n"
"}\n"
"QFrame#frame_left {\n"
"border-bottom: 1px solid white;\n"
"}\n"
"QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_left)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit.setStyleSheet("background-color: #202225;\n"
"color: white;\n"
"border: 0px;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_left)
        self.scrollArea_3.setStyleSheet("background-color: #2F3136;\n"
"QPushButton {\n"
"background-color: white;\n"
"}")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 224, 466))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_3.setStyleSheet("QPushButton {\n"
"background-color: black;\n"
"color: white;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: white;\n"
"color: black;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_3)
        self.frame_2 = QtWidgets.QFrame(self.frame_left)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setStyleSheet("QFrame {\n"
"background-color: #282a2e;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pfp = QtWidgets.QLabel(self.frame_2)
        self.pfp.setScaledContents(True)
        self.pfp.setObjectName("pfp")
        self.horizontalLayout_2.addWidget(self.pfp)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.username = QtWidgets.QLabel(self.frame_2)
        self.username.setObjectName("username")
        self.verticalLayout_3.addWidget(self.username)
        self.tag = QtWidgets.QLabel(self.frame_2)
        self.tag.setObjectName("tag")
        self.verticalLayout_3.addWidget(self.tag)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.account_type = QtWidgets.QLabel(self.frame_left)
        self.account_type.setObjectName("account_type")
        self.verticalLayout_2.addWidget(self.account_type)
        self.button_connect = QtWidgets.QPushButton(self.frame_left)
        self.button_connect.setObjectName("button_connect")
        self.verticalLayout_2.addWidget(self.button_connect)
        self.gridLayout_5.addWidget(self.frame_left, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_home)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame.setStyleSheet("QFrame {\n"
"background-color: #202225;\n"
"}\n"
"QPushButton {\n"
"height: 50px;\n"
"width: 70px;\n"
"border: 1px solid gray;\n"
"background-color: white;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: gray;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #222224;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_home = QtWidgets.QPushButton(self.frame)
        self.button_home.setObjectName("button_home")
        self.verticalLayout.addWidget(self.button_home)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.main_frame = QtWidgets.QFrame(self.tab_home)
        self.main_frame.setStyleSheet("QFrame#main_frame {\n"
"background-color: #36393F;\n"
"border-bottom: 1px solid white;\n"
"}\n"
"QPushButton {\n"
"background-color: #9d9da1;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: white;\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_top = QtWidgets.QFrame(self.main_frame)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_top.setStyleSheet("QFrame{\n"
"border: 1 solid black;\n"
"border-left: 0px;\n"
"border-right: 0px;\n"
"border-top: 0px;\n"
"}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.channel_name = QtWidgets.QLabel(self.frame_top)
        self.channel_name.setStyleSheet("border: 0px;")
        self.channel_name.setObjectName("channel_name")
        self.horizontalLayout_3.addWidget(self.channel_name)
        self.toolButton = QtWidgets.QToolButton(self.frame_top)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.gridLayout_2.addWidget(self.frame_top, 0, 0, 1, 2)
        self.frame_bottom = QtWidgets.QFrame(self.main_frame)
        self.frame_bottom.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_bottom.setStyleSheet("QFrame {\n"
"border-top: 1px solid black;\n"
"}")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_bottom)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.message_send = QtWidgets.QTextEdit(self.frame_bottom)
        self.message_send.setStyleSheet("QTextEdit{\n"
"border-radius: 15px;\n"
"background-color: #6d6d75;\n"
"color: white;\n"
"}\n"
"QTextEdit:hover {\n"
"border: 1px solid white;\n"
"}")
        self.message_send.setAcceptRichText(False)
        self.message_send.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.message_send.setObjectName("message_send")
        self.horizontalLayout.addWidget(self.message_send)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_bottom)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_bottom)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addWidget(self.frame_bottom, 2, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.main_frame)
        self.scrollArea.setStyleSheet("background-color: #36393F;\n"
"border: 0px;\n"
"\n"
"                      ")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 549, 483))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_text = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_text.setStyleSheet("border: 0px;")
        self.frame_text.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text.setObjectName("frame_text")
        self.layout_text = QtWidgets.QVBoxLayout(self.frame_text)
        self.layout_text.setContentsMargins(-1, -1, 11, -1)
        self.layout_text.setObjectName("layout_text")
        self.gridLayout_4.addWidget(self.frame_text, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.scroll_members = QtWidgets.QScrollArea(self.main_frame)
        self.scroll_members.setMinimumSize(QtCore.QSize(70, 0))
        self.scroll_members.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scroll_members.setStyleSheet("background-color: #282a2e;\n"
"border: 0px;\n"
"border-left: #2F3136;")
        self.scroll_members.setWidgetResizable(True)
        self.scroll_members.setObjectName("scroll_members")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 100, 570))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.scroll_members.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scroll_members, 1, 1, 2, 1)
        self.gridLayout_5.addWidget(self.main_frame, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_home, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.tabWidget.addTab(self.tab_settings, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNetwork_status = QtWidgets.QAction(MainWindow)
        self.actionNetwork_status.setObjectName("actionNetwork_status")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuHome.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionNetwork_status)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DiscordClient"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search or find a conversation"))
        self.pfp.setText(_translate("MainWindow", "image"))
        self.username.setText(_translate("MainWindow", "<b>none<b>"))
        self.tag.setText(_translate("MainWindow", "0001"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.account_type.setText(_translate("MainWindow", "Account type: <b>normal<b>"))
        self.button_connect.setText(_translate("MainWindow", "Connect to Discord"))
        self.button_home.setText(_translate("MainWindow", "Home"))
        self.channel_name.setText(_translate("MainWindow", "<h2># Channel name</h2>"))
        self.toolButton.setText(_translate("MainWindow", "Quick tools"))
        self.message_send.setPlaceholderText(_translate("MainWindow", "Message"))
        self.pushButton_5.setText(_translate("MainWindow", "Craft Embed"))
        self.pushButton_3.setText(_translate("MainWindow", "Emoji"))
        self.label.setText(_translate("MainWindow", "members"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_home), _translate("MainWindow", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "Settings"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNetwork_status.setText(_translate("MainWindow", "Network status"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
